config/routes.rb
Rails.application.routes.draw do
  get 'tags', to: "genres#index"
  resources :genres  
  get 'gamerss/index'
  resources :gamereqs
  get 'qc.rss', to: 'gamerss#index', defaults: { format: 'rss' }
  get 'gupdate', to: "games#gupdate"
  get 'qc', to: "forum#index"
  get 'qc/:id', to: 'forum#indexketto', as: 'qct'
  get "backup", to: 'backup#index'
  get "backup_egyszer", to: 'backup#egyszer'
  get "bot_reset", to: "games#bot_reset"
  get "plus_upload", to: "uploads#plus_upload"
  get "minus_upload", to: "uploads#minus_upload"
  get "yttodiscord", to: "games#yttodiscord"
  post "gameforum", to: "games#forum"
  delete "rssdelete", to: "rss#rssdelete"
  get "genreset", to: "games#reset_game_genres"
  post "oldal", to: "games#oldal"
  get "gameforumdelete", to: "games#forumdelete"
  get "gameforumaccept", to: "games#forumaccept"
  get "gamereqsdelete", to: "gamereqs#reqsdelete"
  get "gamereqsaccept", to: "gamereqs#reqsaccept"
  get "gameforumaccept2", to: "games#forumaccept2"
  get "check_username", to: "games#check_username"
  resources :supportlists
  resources :supporters
  resources :uploads
  resources :games
  resources :todos
  resources :forums
  resources :hopps
  resources :autoforditoilists
  resources :projects
  resources :howtos
  resources :changers
  resources :scanners
  resources :cars
  resources :beolvas
  resources :csvs
  resources :databeolvas, to: 'beolvas#soronkent'
  resources :news
  resources :blogs
  resources :programs
  resources :translaters
  resources :platforms
  resources :users
  resources :user2s
  resources :lists
  resources :megas
  root 'games#index'
  get "todo_ok", to: "todos#ok"
  get "todo_nok", to: "todos#nok"
  get "discord", to: "games#discord"
  get 'done_todo', to: 'todos#done'
  post "new_yt", to: "games#new_yt"
  post "edit_yt", to: "games#edit_yt"
  post "delete_yt", to: "games#delete_yt"  
  delete '/pictures/:upload_id/pictures/:image_id', to: 'uploads#picturesdelete', as: 'delete_picture'
  get 'lemondva', to: "lemondva#index"
  get 'lefoglalva', to: "lefoglalva#index"  
  get 'statisztikabot', to: "stat#bot"
  get 'statisztika', to: "stat#sanyi"
  get 'stat/random_data'
  get 'kuki/index'
  get 'kuki/new'
  get 'kuki/create'
  get "bel", to: "games#features"
  get 'facebook', to: "facebook#index"
  get 'rssmagyhu', to: 'rssmagyhu#kan'
  get 'rssmagyhurefresh', to: 'rssmagyhu#index'
  get 'ipadress/index'
  get 'feltoltve', to:  'feltoltve#index'
  get 'supports', to: 'support#index'
  get 'openai/index'
  get 'regexp', to: 'games#regexp'
  get 'magyhu/index'
  get 'magyhu/beolvas'
  get 'search/kereses'
  get 'disqus', to: "disqus#index"
  get 'gmail', to: "gmail#index"
  get "kozelito", to: "beolvas#kozelito"
  get 'reinstall/index'
  get 'reinstall/game_up'
  get "file_process", to: "beolvas#file_process"
  get "file_process_new", to: "beolvas#file_process_new"
  get "igezo", to: "beolvas#igezo"
  get "nyito", to: "beolvas#nyito"
  get "line", to: "beolvas#soronkent"
  get "line_unreal", to: "beolvas#soronkent_unreal"
  get "unreal", to: "beolvas#unreal"
  get "linebyline", to: "beolvas#linebyline"
  post "linebyline_save", to: "beolvas#linebyline_save"
  post "file_download", to: "beolvas#file_download"
  post "revizio", to: "beolvas#revizio"
  post "uzenet", to: "uzenets#uzenet"
  post "muzenet", to: "uzenets#muzenet"
  get "file_download_original", to: "beolvas#file_download_original"
  post "forditas_elmentese", to: "beolvas#translate_save"
  post "forditas_eusave", to: "beolvas#translate_save_eu"
  post "forditas_unreal_save", to: "beolvas#translate_save_unreal"
  post "karakterek_be", to: "beolvas#karakter_save_be"
  post "karakterek_ki", to: "beolvas#karakter_save_ki"
  post "forditas_javitasa", to: "beolvas#igezo_save"
  post "forditas_unreal_javitasa", to: "beolvas#igezo_save_unreal"
  post "tomeges_csere_unreal", to: "beolvas#tomeges_csere_unreal"
  post "file_download_kalap", to: "beolvas#file_download_kalap"
  post "soron_mentes", to: "beolvas#soron_save"
  get "databeolvas_reset", to: "beolvas#databeolvas_reset"
  get "datatranslate_reset", to: "beolvas#datatranslate_reset"
  get "finish", to: "beolvas#finish"
  get "duplikalo", to: "beolvas#duplikalo"
  get "duplikalo_delete", to: "beolvas#duplikalo_delete"
  get "fordsor", to: "beolvas#fordsor"
  post "translateractive", to: "translaters#active"
  post "translaterdeactive", to: "translaters#deactive"
  get "mutasd", to: "beolvas#mutasd"
  get "universal", to: "beolvas#universal"
  post "universal_save", to: "beolvas#universal_save"
  get "delete_uzenet", to:"uzenets#delete_uzenet"
  post "gameforumusermute", to: "games#mute"
  post "gameforumuserunmute", to: "games#unmute"

  get 'lista', to: 'lists#friss'
  get 'mega', to: 'mega#index'
  get 'stat', to: 'stat#index'
  post 'down', to: 'megas#download'
  get 'download_games', to: 'games#download_games'
  get 'check_name', to: 'games#check_name'
  get 'check_steam', to: 'games#check_steam'
  get 'download_file', to: 'games#download_file'
 
  get "user", to: "user2s#index"
  get "recovery", to: "sessions#recovery"
  post "sessions_recovery_mail", to: "sessions#sessions_recovery_mail"
  get "recovery_mail_sent", to: "sessions#recovery_mail_sent"
  get "/recovery_mail", to: "sessions#recovery_mail"
  get "recovery_user", to: "sessions#recovery_user"
  get "new_password_ready", to: "sessions#new_password_ready"
  post 'download', to: "games#download"
  post 'editorka', to: "uploads#editorka"
  post 'lista_editor', to: "lists#editorka"
  post 'megas_editor', to: "megas#editorka"
  post 'upload_bad', to: "uploads#bad"
  post 'games_magyhu', to: "games#magyhu"
  get 'feloldas', to: 'games#feloldas'
  
  get 'rssgemo', to:  'rss#index'
  get 'lemondva', to:  'lemondva#index'
  
  get 'sessions/new'
  get 'sessions/create'
  get 'login/signin', to: 'sessions#new'
  get 'login/signout'
  get 'login/reg'
  get 'tomb', to: 'lists#tomb'
  post 'tomb', to: 'lists#tomb_feldolgozo'
  get 'lists_update', to: 'lists#lista_frissites'

post 'login/create'
post 'sessions/create'
get 'login/create', to: 'login#reg'
get "fbn", to: "projects#fajlok_beolvasasa_normal"
get "project_trans_reset", to: "projects#project_trans_reset"
get "ptf", to: "projects#project_tomeges_forditas"
get "ptfo", to: "projects#project_tomeges_forditas_osszes"
post "project_oszlop", to: "projects#project_oszlop"
post "project_szoveg", to: "projects#project_szoveg"
post "project_elvalaszto", to: "projects#project_elvalaszto"
post "project_mentes", to: "projects#project_forditas_mentes"
post "project_nemvalto", to: "projects#project_nemvalto"
post "project_sorvalto", to: "projects#project_sorvalto"
get "project_file_download_kalap", to: "projects#project_file_download_kalap"
get "project_finish", to: "projects#project_finish"
get "project_line", to: "projects#line"
get "project_lines", to: "projects#lines"
get "project_file_zip", to: "projects#project_file_zip"
post "project_line_javitasa", to: "projects#project_line_save"
get "rendezo", to: "projects#rendezo"
post "project_tomeges_csere", to: "projects#tomeges_csere"
post 'project_download', to: "projects#download"
get 'project_download', to: "projects#download"
post 'project_paros', to: "projects#project_paros"
get "project_idezojel", to: "projects#idezojel"
get "project_nyito", to: "projects#nyito"
post "project_idezo_mentes", to: "projects#idezojel_mentes"
post "project_char_on", to: "projects#char_on"
post "project_char_off", to: "projects#char_off"
post "project_regex", to: "projects#regex"
post "translatertouser", to: "user2s#translatertouser"
get "search", to: "search#kereses"
get "searchmagyhu", to: "search#keresesmagyhu"
get "searchtl", to: "search#keresestl"
get "magyhu", to: "magyhu#beolvas"
get "downloadend", to: "games#downloadend"
get "jakab", to: "games#jakab"
get 'download_ticket/:id', to: 'tickets#download_ticket', as: 'download_ticket'
get 'filem', to: "projects#filem"
post 'lobot', to: "games#lobot"
get "hopper", to: "hopps#hopper"
get "regenerated", to: "translaters#regen"

end

app/models/translater.rb
class Translater < ApplicationRecord
    has_many :uploads
    has_many :uploadtranslaters
    validates :translater_name, uniqueness: true, presence: true, length: {minimum: 2, maximum:100}
    has_one :user
    extend FriendlyId
    friendly_id :translater_name, use: :slugged
    def should_generate_new_friendly_id?
        translater_name_changed?
    end
    def generate_and_save_slug
        self.slug = self.translater_name.parameterize
        self.save
    end
end

app/controllers/translaters_controller.rb
class TranslatersController < ApplicationController
  before_action :set_translater, only: %i[ show edit update destroy ]
  before_action :authorized?, only: %i[new edit update destroy]
  
  # GET /translaters or /translaters.json
  def index
    @translaters = Translater.where(active: true).all.order(translater_name: :ASC)
    @translaters_rest = Translater.where(active: false).order(translater_name: :ASC)
    
    @upload = Upload.order("created_at DESC").first(10)
    @download = Download.order("created_at DESC").first(10)
   
  end
  def active
    if current_user.admin?
      trans = Translater.find(params[:id])
      trans.update(active: true)
    end
  end
  def deactive
    if current_user.admin?
      trans = Translater.find(params[:id])
      trans.update(active: false)
    end
  end
  # GET /translaters/1 or /translaters/1.json
  def show
    @feltoltesek = Upload.where(translater_id: params[:id]).order(id: :DESC)
    @upload = Upload.order("created_at DESC").first(10)
    @download = Download.order("created_at DESC").first(10)
    translater = Translater.where(slug: params[:id]).first
    user = User.where(translater_id: translater.id).first
    if user      
      @supportlist = Supportlist.where(user_id: user)
    end
  end

  # GET /translaters/new
  def new
    @translater = Translater.new
  end

  # GET /translaters/1/edit
  def edit
  end
  
  # POST /translaters or /translaters.json
  def create
    @translater = Translater.new(translater_params)

    respond_to do |format|
      if @translater.save
        format.html { redirect_to translater_url(@translater), notice: "Translater was successfully created." }
        format.json { render :show, status: :created, location: @translater }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @translater.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /translaters/1 or /translaters/1.json
  def update
    respond_to do |format|
      if @translater.update(translater_params)
        format.html { redirect_to translater_url(@translater), notice: "Translater was successfully updated." }
        format.json { render :show, status: :ok, location: @translater }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @translater.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /translaters/1 or /translaters/1.json
  def destroy
    @translater.destroy

    respond_to do |format|
      format.html { redirect_to translaters_url, notice: "Translater was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  def regen
    translaters = Translater.all

    # Iterál a rekordokon és hívja meg a generate_and_save_slug methodot mindegyikre
    translaters.each do |translater|
    translater.generate_and_save_slug
  end
end

#Ex:- :default =>''
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_translater
      @translater = Translater.friendly.find(params[:id])
      
    end

    # Only allow a list of trusted parameters through.
    def translater_params
      params.require(:translater).permit(:translater_name)
    end
end

app/helpers/translaters_helper.rb
module TranslatersHelper

    def forditasok(id)
        feltoltesek = Upload.where(translater_id: id).order(id: :DESC).first(10)
    end
    
    def transtop(id)
        translater_id = id
        ingwer = ""
        intem = 1
        top_downloads = Download.group(:upload_id).count.sort_by { |_, count| -count }
        top_downloads.each do |upload_id, count|
            upload = Upload.find(upload_id)            
          if Uploadtranslater.exists?(upload_id: upload_id, translater_id: translater_id)
            ingwer += " <a href=\"/games/#{upload.game.slug}\" class=\"btn bg-dark bg-gradient text-light\" style=\"text-decoration: none; color: #333;\"> #{intem}. #{upload.game.name} (#{count}) »</a> <br>"
            intem += 1
            break if intem > 10  # Kilépés a ciklusból, ha intem értéke 10
          end
        end
        ingwer
      end

end

app/views/translaters/_form.html.slim
= form_for @translater do |f|
  - if @translater.errors.any?
    #error_explanation.bg-secondary
      h2 = "#{pluralize(@translater.errors.count, 'error')} prohibited this upload from being saved:"
      ul
        - @translater.errors.full_messages.each do |message|
          li = message
  = f.label :translater_name
  = f.text_field :translater_name
 
  
  .actions = f.submit 'Új feltöltő felvétele', class: "btn btn-success"

app/views/translaters/edit.html.slim
h1 Editing Translater

== render 'form'

=> link_to 'Show', @translater
'|
=< link_to 'Back', translaters_path

app/views/translaters/index.html copy.slim
h1 Fordítások készítői:

table.table.table-dark
  thead
    tr
      th Neve
      th Fordítás
      th Játék 
      th Fájlnév 
      th Letöltve
      - if current_user.present?
          - if current_user.admin?
            th Actions

  tbody
    - @translaters.each do |t|
      




      tr
        td = t.translater_name 
        td = Upload.where(translater_id: t.id).count
        td 
          table.table-striped.table-hover.text-light.orulet

            - Upload.where(translater_id: t.id).order(:name).each do |pd|
              tr.oruletes
                td style="width:400px" 
                  = pd.name
                td style="width:200px" 
                  = pd.version
                td style="width:1000px" 
                  =pd.game_files.filename
                td.col-2 
                  =pd.download.count
              
        
        
        - if current_user.present?
          - if current_user.admin?
            td 
              = link_to 'Show', t , class:"btn btn-primary mr-2"
              = link_to 'Edit', edit_translater_path(t), class:"btn btn-primary mr-2"
              = link_to 'Destroy', t, data: { confirm: 'Are you sure?' }, method: :delete, class:"btn btn-primary mr-2"

br
- if current_user.present?
  - if current_user.admin?
    = link_to 'New Translater', new_translater_path

.card-container
  span.pro
    | PRO
  img.round[src="https://xsgames.co/randomusers/avatar.php?g=male" alt="user"]
  h3
    | Ricky Park
  h6
    | New York
  p
    | User interface designer and 
    br
    |  front-end developer
  .buttons
    button.primary
      |  Message 
    button.primary.ghost
      |  Following 
  .skills
    h6
      | Skills
    ul
      li
        | UI / UX
      li
        | Front End Development
      li
        | HTML
      li
        | CSS
      li
        | JavaScript
      li
        | React
      li
        | Node

app/views/translaters/index.html.slim
.container-flex
  .row 
    .col-xs-12.col-md-9.col-lg-10.bg-basic-color
      .row
        .col-12.bg-info.text-center
          H1 Jelenleg is aktív fordítóink
        
        - if current_user.present?
          - if current_user.admin?
            = link_to 'Új fordító felvétele', new_translater_path, class:"btn btn-success"
        - @translaters.each do |t|
          .col-sx-12.col-sm-3
            .creator-card
              = link_to translater_path(t.slug)
                .creator-card__img
                  = image_tag("ize/2.svg", class: "img-fluid")
                h4
                  = t.translater_name
                  br
                  |Fordítások:
                  = Uploadtranslater.where(translater_id: t).size
      .row
        .col-12.bg-info.text-center
          H1 Már nem aktív fordítók
        - @translaters_rest.each do |t|
          .col-sx-12.col-sm-3
            .creator-card
              = link_to translater_path(t.slug)
                .creator-card__img
                  -if current_user&.admin?
                    -if t.active?
                      h1 AKTÍV
                  = image_tag("ize/2.svg", class: "img-fluid")
                h4
                  = t.translater_name
                  br
                  |Fordítások:
                  = Uploadtranslater.where(translater_id: t).size
    .col-xs-12.col-md-3.col-lg-2.bg-grey-color.side-scroll
      = render 'shared/side' 
      

app/views/translaters/new.html.slim
h1 Új fordító feltöltése:
.container.shadow
    == render 'form'

    = link_to 'Back', translaters_path

app/views/translaters/show.html.slim
.container-fluid
  .row
    .col-xs-12.col-md-9.col-lg-10.bg-basic-color.text-light
      h1.creator-data-name
        = @translater.translater_name
      - if current_user&.admin?
        -if @translater.active?
          = link_to "Nem Aktív", translaterdeactive_path(id: @translater.id), method: "post", class:"btn btn-success"
        - else
          = link_to "Aktív", translateractive_path(id: @translater.id),method: "post", class:"btn btn-success"
      .row
        .col-xs-12.col-sm-12.col-md-3
          - if @translater.user.present?
            - if @translater.user.photo.attached?
              = image_tag @translater.user.photo , class: "img-fluid"
          -else
            = image_tag("ize/2.svg", class: "img-fluid")
        .col-xs-12.col-sm-12.col-md-9
          .creator-data-text
            - if @translater.user.present?
              h2
                | Bemutatkozás
              p
          
                - if @translater.user.desc.present?
                  = @translater.user.desc
                br
                - if @supportlist
                  |Támogasd a munkám, ha megteheted:
                  br
                  -@supportlist.each do |support|
                    = link_to support.link,class:"btn btn-secondary mt-3", target: "_blank" do |link|
                      = raw(support.iconbootstrap.gsub('"></', ' m-1"></'))
                      = support.name
                    br
                  
                
                
                
                
                  
          //h2  Top10
          //= transtop(@translater).html_safe
          h2
            |Utolsó 10 fordítása:
            .row
              - Uploadtranslater.where(translater_id: @translater).order(id: :DESC).distinct.first(10).each do |t|
                .col-6
                  a.cards href="/games/#{t.upload.game.slug}"                  
                    = image_tag(t.upload.game.image.variant(resize_to_fit: [492, 282]), class: 'listpage-imgs m-2', title: t.upload.game.name) if t.upload.game.image.attached?
          main role="main"
          
            
      = link_to 'Vissza', translaters_path, class: "btn btn-primary"
    
    .col-xs-12.col-md-3.col-lg-2.bg-grey-color.side-scroll
      = render 'shared/side' 