config/routes.rb
Rails.application.routes.draw do
  get 'tags', to: "genres#index"
  resources :genres  
  get 'gamerss/index'
  resources :gamereqs
  get 'qc.rss', to: 'gamerss#index', defaults: { format: 'rss' }
  get 'gupdate', to: "games#gupdate"
  get 'qc', to: "forum#index"
  get 'qc/:id', to: 'forum#indexketto', as: 'qct'
  get "backup", to: 'backup#index'
  get "backup_egyszer", to: 'backup#egyszer'
  get "bot_reset", to: "games#bot_reset"
  get "plus_upload", to: "uploads#plus_upload"
  get "minus_upload", to: "uploads#minus_upload"
  get "yttodiscord", to: "games#yttodiscord"
  post "gameforum", to: "games#forum"
  delete "rssdelete", to: "rss#rssdelete"
  get "genreset", to: "games#reset_game_genres"
  post "oldal", to: "games#oldal"
  get "gameforumdelete", to: "games#forumdelete"
  get "gameforumaccept", to: "games#forumaccept"
  get "gamereqsdelete", to: "gamereqs#reqsdelete"
  get "gamereqsaccept", to: "gamereqs#reqsaccept"
  get "gameforumaccept2", to: "games#forumaccept2"
  get "check_username", to: "games#check_username"
  resources :supportlists
  resources :supporters
  resources :uploads
  resources :games
  resources :todos
  resources :forums
  resources :hopps
  resources :autoforditoilists
  resources :projects
  resources :howtos
  resources :changers
  resources :scanners
  resources :cars
  resources :beolvas
  resources :csvs
  resources :databeolvas, to: 'beolvas#soronkent'
  resources :news
  resources :blogs
  resources :programs
  resources :translaters
  resources :platforms
  resources :users
  resources :user2s
  resources :lists
  resources :megas
  root 'games#index'
  get "todo_ok", to: "todos#ok"
  get "todo_nok", to: "todos#nok"
  get "discord", to: "games#discord"
  get 'done_todo', to: 'todos#done'
  post "new_yt", to: "games#new_yt"
  post "edit_yt", to: "games#edit_yt"
  post "delete_yt", to: "games#delete_yt"  
  delete '/pictures/:upload_id/pictures/:image_id', to: 'uploads#picturesdelete', as: 'delete_picture'
  get 'lemondva', to: "lemondva#index"
  get 'lefoglalva', to: "lefoglalva#index"  
  get 'statisztikabot', to: "stat#bot"
  get 'statisztika', to: "stat#sanyi"
  get 'stat/random_data'
  get 'kuki/index'
  get 'kuki/new'
  get 'kuki/create'
  get "bel", to: "games#features"
  get 'facebook', to: "facebook#index"
  get 'rssmagyhu', to: 'rssmagyhu#kan'
  get 'rssmagyhurefresh', to: 'rssmagyhu#index'
  get 'ipadress/index'
  get 'feltoltve', to:  'feltoltve#index'
  get 'supports', to: 'support#index'
  get 'openai/index'
  get 'regexp', to: 'games#regexp'
  get 'magyhu/index'
  get 'magyhu/beolvas'
  get 'search/kereses'
  get 'disqus', to: "disqus#index"
  get 'gmail', to: "gmail#index"
  get "kozelito", to: "beolvas#kozelito"
  get 'reinstall/index'
  get 'reinstall/game_up'
  get "file_process", to: "beolvas#file_process"
  get "file_process_new", to: "beolvas#file_process_new"
  get "igezo", to: "beolvas#igezo"
  get "nyito", to: "beolvas#nyito"
  get "line", to: "beolvas#soronkent"
  get "line_unreal", to: "beolvas#soronkent_unreal"
  get "unreal", to: "beolvas#unreal"
  get "linebyline", to: "beolvas#linebyline"
  post "linebyline_save", to: "beolvas#linebyline_save"
  post "file_download", to: "beolvas#file_download"
  post "revizio", to: "beolvas#revizio"
  post "uzenet", to: "uzenets#uzenet"
  post "muzenet", to: "uzenets#muzenet"
  get "file_download_original", to: "beolvas#file_download_original"
  post "forditas_elmentese", to: "beolvas#translate_save"
  post "forditas_eusave", to: "beolvas#translate_save_eu"
  post "forditas_unreal_save", to: "beolvas#translate_save_unreal"
  post "karakterek_be", to: "beolvas#karakter_save_be"
  post "karakterek_ki", to: "beolvas#karakter_save_ki"
  post "forditas_javitasa", to: "beolvas#igezo_save"
  post "forditas_unreal_javitasa", to: "beolvas#igezo_save_unreal"
  post "tomeges_csere_unreal", to: "beolvas#tomeges_csere_unreal"
  post "file_download_kalap", to: "beolvas#file_download_kalap"
  post "soron_mentes", to: "beolvas#soron_save"
  get "databeolvas_reset", to: "beolvas#databeolvas_reset"
  get "datatranslate_reset", to: "beolvas#datatranslate_reset"
  get "finish", to: "beolvas#finish"
  get "duplikalo", to: "beolvas#duplikalo"
  get "duplikalo_delete", to: "beolvas#duplikalo_delete"
  get "fordsor", to: "beolvas#fordsor"
  post "translateractive", to: "translaters#active"
  post "translaterdeactive", to: "translaters#deactive"
  get "mutasd", to: "beolvas#mutasd"
  get "universal", to: "beolvas#universal"
  post "universal_save", to: "beolvas#universal_save"
  get "delete_uzenet", to:"uzenets#delete_uzenet"
  post "gameforumusermute", to: "games#mute"
  post "gameforumuserunmute", to: "games#unmute"

  get 'lista', to: 'lists#friss'
  get 'mega', to: 'mega#index'
  get 'stat', to: 'stat#index'
  post 'down', to: 'megas#download'
  get 'download_games', to: 'games#download_games'
  get 'check_name', to: 'games#check_name'
  get 'check_steam', to: 'games#check_steam'
  get 'download_file', to: 'games#download_file'
 
  get "user", to: "user2s#index"
  get "recovery", to: "sessions#recovery"
  post "sessions_recovery_mail", to: "sessions#sessions_recovery_mail"
  get "recovery_mail_sent", to: "sessions#recovery_mail_sent"
  get "/recovery_mail", to: "sessions#recovery_mail"
  get "recovery_user", to: "sessions#recovery_user"
  get "new_password_ready", to: "sessions#new_password_ready"
  post 'download', to: "games#download"
  post 'editorka', to: "uploads#editorka"
  post 'lista_editor', to: "lists#editorka"
  post 'megas_editor', to: "megas#editorka"
  post 'upload_bad', to: "uploads#bad"
  post 'games_magyhu', to: "games#magyhu"
  get 'feloldas', to: 'games#feloldas'
  
  get 'rssgemo', to:  'rss#index'
  get 'lemondva', to:  'lemondva#index'
  
  get 'sessions/new'
  get 'sessions/create'
  get 'login/signin', to: 'sessions#new'
  get 'login/signout'
  get 'login/reg'
  get 'tomb', to: 'lists#tomb'
  post 'tomb', to: 'lists#tomb_feldolgozo'
  get 'lists_update', to: 'lists#lista_frissites'

post 'login/create'
post 'sessions/create'
get 'login/create', to: 'login#reg'
get "fbn", to: "projects#fajlok_beolvasasa_normal"
get "project_trans_reset", to: "projects#project_trans_reset"
get "ptf", to: "projects#project_tomeges_forditas"
get "ptfo", to: "projects#project_tomeges_forditas_osszes"
post "project_oszlop", to: "projects#project_oszlop"
post "project_szoveg", to: "projects#project_szoveg"
post "project_elvalaszto", to: "projects#project_elvalaszto"
post "project_mentes", to: "projects#project_forditas_mentes"
post "project_nemvalto", to: "projects#project_nemvalto"
post "project_sorvalto", to: "projects#project_sorvalto"
get "project_file_download_kalap", to: "projects#project_file_download_kalap"
get "project_finish", to: "projects#project_finish"
get "project_line", to: "projects#line"
get "project_lines", to: "projects#lines"
get "project_file_zip", to: "projects#project_file_zip"
post "project_line_javitasa", to: "projects#project_line_save"
get "rendezo", to: "projects#rendezo"
post "project_tomeges_csere", to: "projects#tomeges_csere"
post 'project_download', to: "projects#download"
get 'project_download', to: "projects#download"
post 'project_paros', to: "projects#project_paros"
get "project_idezojel", to: "projects#idezojel"
get "project_nyito", to: "projects#nyito"
post "project_idezo_mentes", to: "projects#idezojel_mentes"
post "project_char_on", to: "projects#char_on"
post "project_char_off", to: "projects#char_off"
post "project_regex", to: "projects#regex"
post "translatertouser", to: "user2s#translatertouser"
get "search", to: "search#kereses"
get "searchmagyhu", to: "search#keresesmagyhu"
get "searchtl", to: "search#keresestl"
get "magyhu", to: "magyhu#beolvas"
get "downloadend", to: "games#downloadend"
get "jakab", to: "games#jakab"
get 'download_ticket/:id', to: 'tickets#download_ticket', as: 'download_ticket'
get 'filem', to: "projects#filem"
post 'lobot', to: "games#lobot"
get "hopper", to: "hopps#hopper"
get "regenerated", to: "translaters#regen"

end

app/models/autoforditoilist.rb
class Autoforditoilist < ApplicationRecord
  belongs_to :game
  def self.ransackable_attributes(auth_object = nil)
    [ "gname"]
  end

end

app/controllers/autoforditoilists_controller.rb
class AutoforditoilistsController < ApplicationController
  before_action :set_autoforditoilist, only: %i[ show edit update destroy ]
  def index
    @q1 = Autoforditoilist.ransack(params[:q])
    if params[:q] && params[:q].fetch(:gname_cont, "").size > 2
      @autoforditoilists = @q1.result(distinct: true)
    else      
      @autoforditoilists = Autoforditoilist.where(id: 0)
    end

    @xunity = Autoforditoilist.where(tipus: 1).order(gname: :ASC)
    @xunityf = Autoforditoilist.where(tipus: 3).order(gname: :ASC)
    @bep = Autoforditoilist.where(tipus: 2).order(gname: :ASC)
    @bepf = Autoforditoilist.where(tipus: 4).order(gname: :ASC)
    @ransack_path = autoforditoilists_path
  end

  def show
  end

  def new
    @autoforditoilist = Autoforditoilist.new
    end

  def edit
  end

  def create
    @autoforditoilist = Autoforditoilist.new(autoforditoilist_params)
    @autoforditoilist.gname = Game.find(autoforditoilist_params[:game_id]).name
  
    respond_to do |format|
      if @autoforditoilist.save
        game = Game.find(autoforditoilist_params[:game_id])
        game.uploaded_at = DateTime.now
        game.save
        format.html { redirect_to game_path(game), notice: "Autoforditoilist was successfully created." }
        format.json { render :show, status: :created, location: @autoforditoilist }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @autoforditoilist.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @autoforditoilist.update(autoforditoilist_params)
        format.html { redirect_to autoforditoilist_url(@autoforditoilist), notice: "Autoforditoilist was successfully updated." }
        
      else
        format.html { render :edit, status: :unprocessable_entity }
        
      end
    end
  end

  # DELETE /autoforditoilists/1 or /autoforditoilists/1.json
  def destroy
    @autoforditoilist.destroy

    respond_to do |format|
      format.html { redirect_to autoforditoilists_url, notice: "Autoforditoilist was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_autoforditoilist
      @autoforditoilist = Autoforditoilist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def autoforditoilist_params
      params.require(:autoforditoilist).permit(:game_id, :tipus, :active)
    end
end

app/helpers/autoforditoilists_helper.rb
module AutoforditoilistsHelper
end

app/views/autoforditoilists/_autoforditoilist.html.slim
div id="#{dom_id autoforditoilist}"
  p
    strong Game:
    =< autoforditoilist.game_id
  p
    strong Tipus:
    =< autoforditoilist.tipus
  p
    strong Active:
    =< autoforditoilist.active

app/views/autoforditoilists/_form.html.slim
.container-fluid
  .row
    .col-xs-12.col-md-9.col-lg-10.bg-basic-color
      .row
        .col-xs-12.col-sm-12.col-md-6.offset-md-3.col-lg-4.offset-lg-4.d-flex.flex-column.align-content-center.text-light
          - if @autoforditoilist.errors.any?
      
            h2 = "#{pluralize(@autoforditoilist.errors.count, "error")} hiba történt a mentés közben:"
            ul
              - @autoforditoilist.errors.full_messages.each do |message|
                li = message
      .row
        .col-xs-12.col-sm-12.col-md-6.offset-md-3.col-lg-4.offset-lg-4.d-flex.flex-column.align-content-center
          .form
            h1.form__headline
              - if @autoforditoilist.persisted?
                |  Adatlap módosítás
              - else 
                |  Új játék adatlap
              = form_with(model: @autoforditoilist) do |form|
                - if @autoforditoilist.errors.any?
                  div style="color: red"
                    h2 = "#{pluralize(@autoforditoilist.errors.count, "error")} prohibited this autoforditoilist from being saved:"
                    ul
                      - @autoforditoilist.errors.each do |error|
                        li = error.full_message

                = form.text_field :game_id, value: params[:game_id], class: "mb-2",placeholder: "game_id"
                br
                = form.collection_select :tipus, [["XUnity 1m", 1],["BepInEx 10m", 2],["XUnity + Font 27m", 3],["Bep + Font 39m", 4]], :last, :first, prompt: true, class: "block mb-2"
                br
                = form.label :active
                = form.check_box :active
                br
                - if @autoforditoilist.persisted?
                  = form.submit "Módosítás »" , class: "btn btn-primary"
                - else 
                  = form.submit "Felvétel »" , class: "btn btn-primary"
          = link_to "Back to autoforditoilists", autoforditoilists_path, class:"btn btn-primary"
                
    .col-xs-12.col-md-3.col-lg-2.bg-grey-color.side-scroll
      = render 'shared/side' 


            

app/views/autoforditoilists/edit.html.slim
h1 Editing autoforditoilist

== render "form", autoforditoilist: @autoforditoilist

br

div
  => link_to "Show this autoforditoilist", @autoforditoilist
  '|
  =< link_to "Back to autoforditoilists", autoforditoilists_path

app/views/autoforditoilists/index.html.slim
.container-fluid
  .row
    .col-xs-12.col-md-9.col-lg-10.bg-basic-color 
      .row.justify-content-center.align-items-center
        .col-xs-12.col-md-9.col-lg-10.text-center.text-light.rounded style="background: #344b57;"
          p style="color: green" = notice

          h1 Automatikus fordítók
          h3
            |Az automatikus fordító programok élőben, a játék során az internet segítségével fordítják a játékokat.
            br
            |Ez esetben nincsenek a játékok lefordítva, hanem a DEEPL és a GOOGLE fordító erejét segítségül hívva, online fordítja a program a UNITY motorral meghajtott programokat.
            br
            |Semmilyen különleges előkészületet nem igényelnek ezek a programok. 
            br
            |Egyszerűen töltsd le a játéknak megfelelő automatikus fordítót, és élvezd magyar nyelven a játékot.
            br
            |A fordító programoknak szükséges ONLINE internet elérés, mert e nélkül nem működik.
            br
            |Jelenleg 2 féle programot különböztetünk meg.
            br
            br
            .row 
               = search_form_for @q1 , class: "pityuka", url: @ransack_path do |f|
                  = f.text_field :gname_cont, placeholder: "Gyors kereső..."
            - if @autoforditoilists.any?
              | Találat: 
              - @autoforditoilists.each do |todor|
                = todor.game.name
                - case todor.tipus
                  -when 1
                    = link_to "XUnity letöltése", "/files/xunity.zip", download: "xunity.zip", class: "btn btn-primary m-3 "
                  -when 2
                    = link_to "BepInEx letöltése", "/files/bep.zip", download: "bep.zip", class: "btn btn-primary m-3 "
                  -when 3
                    = link_to "XUnity + Font letöltése", "/files/xunityfont.zip", download: "xunityfont.zip", class: "btn btn-primary m-3"
                  -when 4
                    = link_to "BepInEx + Font letöltése", "/files/bepf.zip", download: "bepf.zip", class: "btn btn-primary m-3"
                  -else
                    |(Hiba)
                br
                  
                
            .row 
              .col-3 
                table class="table table-dark table-striped table-bordered"
                  thead
                    tr
                      th 
                        |XUnity 
                        = link_to "Letöltés", "/files/xunity.zip", download: "xunity.zip", class: "btn btn-primary "

                  tbody
                    - @xunity.each do |xu|
                      tr
                        td 
                          = xu.game.name
                         
                      
               
              .col-3 
                table class="table table-dark table-striped table-bordered"
                  thead
                    tr
                      th 
                        |XUnity + font 
                        = link_to "Letöltés", "/files/xunityfont.zip", download: "xunityfont.zip", class: "btn btn-primary "

                  tbody
                    - @xunityf.each do |xuf|
                      tr
                        td 
                           = xuf.game.name
                        
              .col-3 
                table class="table table-dark table-striped table-bordered"
                  thead
                    tr
                      th 
                        |BepInEx  
                        = link_to "Letöltés", "/files/bep.zip", download: "bep.zip", class: "btn btn-primary "
                  tbody
                    - @bep.each do |bep|
                      tr
                        td = bep.game.name
                    
              .col-3 
                table class="table table-dark table-striped table-bordered"
                  thead
                    tr
                      th 
                        |BepInEx + Font 
                        = link_to "Letöltés", "/files/bepf.zip", download: "bepf.zip", class: "btn btn-primary "
                  tbody
                    - @bepf.each do |bepf|
                      tr
                        td = bepf.game.name  
                


          - if current_user&.admin?
            = link_to "New autoforditoilist", new_autoforditoilist_path
    .col-xs-12.col-md-3.col-lg-2.bg-grey-color.side-scroll
        = render 'shared/side' 

app/views/autoforditoilists/new.html.slim
- if current_user&.admin?
  == render "form", autoforditoilist: @autoforditoilist
  
- else 
  h1 nincs jogod

app/views/autoforditoilists/show.html.slim
p style="color: green" = notice

== render @autoforditoilist

div
  => link_to "Edit this autoforditoilist", edit_autoforditoilist_path(@autoforditoilist)
  '|
  =< link_to "Back to autoforditoilists", autoforditoilists_path

  = button_to "Destroy this autoforditoilist", @autoforditoilist, method: :delete