config/routes.rb
Rails.application.routes.draw do
  get 'tags', to: "genres#index"
  resources :genres  
  get 'gamerss/index'
  resources :gamereqs
  get 'qc.rss', to: 'gamerss#index', defaults: { format: 'rss' }
  get 'gupdate', to: "games#gupdate"
  get 'qc', to: "forum#index"
  get 'qc/:id', to: 'forum#indexketto', as: 'qct'
  get "backup", to: 'backup#index'
  get "backup_egyszer", to: 'backup#egyszer'
  get "bot_reset", to: "games#bot_reset"
  get "plus_upload", to: "uploads#plus_upload"
  get "minus_upload", to: "uploads#minus_upload"
  get "yttodiscord", to: "games#yttodiscord"
  post "gameforum", to: "games#forum"
  delete "rssdelete", to: "rss#rssdelete"
  get "genreset", to: "games#reset_game_genres"
  post "oldal", to: "games#oldal"
  get "gameforumdelete", to: "games#forumdelete"
  get "gameforumaccept", to: "games#forumaccept"
  get "gamereqsdelete", to: "gamereqs#reqsdelete"
  get "gamereqsaccept", to: "gamereqs#reqsaccept"
  get "gameforumaccept2", to: "games#forumaccept2"
  get "check_username", to: "games#check_username"
  resources :supportlists
  resources :supporters
  resources :uploads
  resources :games
  resources :todos
  resources :forums
  resources :hopps
  resources :autoforditoilists
  resources :projects
  resources :howtos
  resources :changers
  resources :scanners
  resources :cars
  resources :beolvas
  resources :csvs
  resources :databeolvas, to: 'beolvas#soronkent'
  resources :news
  resources :blogs
  resources :programs
  resources :translaters
  resources :platforms
  resources :users
  resources :user2s
  resources :lists
  resources :megas
  root 'games#index'
  get "todo_ok", to: "todos#ok"
  get "todo_nok", to: "todos#nok"
  get "discord", to: "games#discord"
  get 'done_todo', to: 'todos#done'
  post "new_yt", to: "games#new_yt"
  post "edit_yt", to: "games#edit_yt"
  post "delete_yt", to: "games#delete_yt"  
  delete '/pictures/:upload_id/pictures/:image_id', to: 'uploads#picturesdelete', as: 'delete_picture'
  get 'lemondva', to: "lemondva#index"
  get 'lefoglalva', to: "lefoglalva#index"  
  get 'statisztikabot', to: "stat#bot"
  get 'statisztika', to: "stat#sanyi"
  get 'stat/random_data'
  get 'kuki/index'
  get 'kuki/new'
  get 'kuki/create'
  get "bel", to: "games#features"
  get 'facebook', to: "facebook#index"
  get 'rssmagyhu', to: 'rssmagyhu#kan'
  get 'rssmagyhurefresh', to: 'rssmagyhu#index'
  get 'ipadress/index'
  get 'feltoltve', to:  'feltoltve#index'
  get 'supports', to: 'support#index'
  get 'openai/index'
  get 'regexp', to: 'games#regexp'
  get 'magyhu/index'
  get 'magyhu/beolvas'
  get 'search/kereses'
  get 'disqus', to: "disqus#index"
  get 'gmail', to: "gmail#index"
  get "kozelito", to: "beolvas#kozelito"
  get 'reinstall/index'
  get 'reinstall/game_up'
  get "file_process", to: "beolvas#file_process"
  get "file_process_new", to: "beolvas#file_process_new"
  get "igezo", to: "beolvas#igezo"
  get "nyito", to: "beolvas#nyito"
  get "line", to: "beolvas#soronkent"
  get "line_unreal", to: "beolvas#soronkent_unreal"
  get "unreal", to: "beolvas#unreal"
  get "linebyline", to: "beolvas#linebyline"
  post "linebyline_save", to: "beolvas#linebyline_save"
  post "file_download", to: "beolvas#file_download"
  post "revizio", to: "beolvas#revizio"
  post "uzenet", to: "uzenets#uzenet"
  post "muzenet", to: "uzenets#muzenet"
  get "file_download_original", to: "beolvas#file_download_original"
  post "forditas_elmentese", to: "beolvas#translate_save"
  post "forditas_eusave", to: "beolvas#translate_save_eu"
  post "forditas_unreal_save", to: "beolvas#translate_save_unreal"
  post "karakterek_be", to: "beolvas#karakter_save_be"
  post "karakterek_ki", to: "beolvas#karakter_save_ki"
  post "forditas_javitasa", to: "beolvas#igezo_save"
  post "forditas_unreal_javitasa", to: "beolvas#igezo_save_unreal"
  post "tomeges_csere_unreal", to: "beolvas#tomeges_csere_unreal"
  post "file_download_kalap", to: "beolvas#file_download_kalap"
  post "soron_mentes", to: "beolvas#soron_save"
  get "databeolvas_reset", to: "beolvas#databeolvas_reset"
  get "datatranslate_reset", to: "beolvas#datatranslate_reset"
  get "finish", to: "beolvas#finish"
  get "duplikalo", to: "beolvas#duplikalo"
  get "duplikalo_delete", to: "beolvas#duplikalo_delete"
  get "fordsor", to: "beolvas#fordsor"
  post "translateractive", to: "translaters#active"
  post "translaterdeactive", to: "translaters#deactive"
  get "mutasd", to: "beolvas#mutasd"
  get "universal", to: "beolvas#universal"
  post "universal_save", to: "beolvas#universal_save"
  get "delete_uzenet", to:"uzenets#delete_uzenet"
  post "gameforumusermute", to: "games#mute"
  post "gameforumuserunmute", to: "games#unmute"

  get 'lista', to: 'lists#friss'
  get 'mega', to: 'mega#index'
  get 'stat', to: 'stat#index'
  post 'down', to: 'megas#download'
  get 'download_games', to: 'games#download_games'
  get 'check_name', to: 'games#check_name'
  get 'check_steam', to: 'games#check_steam'
  get 'download_file', to: 'games#download_file'
 
  get "user", to: "user2s#index"
  get "recovery", to: "sessions#recovery"
  post "sessions_recovery_mail", to: "sessions#sessions_recovery_mail"
  get "recovery_mail_sent", to: "sessions#recovery_mail_sent"
  get "/recovery_mail", to: "sessions#recovery_mail"
  get "recovery_user", to: "sessions#recovery_user"
  get "new_password_ready", to: "sessions#new_password_ready"
  post 'download', to: "games#download"
  post 'editorka', to: "uploads#editorka"
  post 'lista_editor', to: "lists#editorka"
  post 'megas_editor', to: "megas#editorka"
  post 'upload_bad', to: "uploads#bad"
  post 'games_magyhu', to: "games#magyhu"
  get 'feloldas', to: 'games#feloldas'
  
  get 'rssgemo', to:  'rss#index'
  get 'lemondva', to:  'lemondva#index'
  
  get 'sessions/new'
  get 'sessions/create'
  get 'login/signin', to: 'sessions#new'
  get 'login/signout'
  get 'login/reg'
  get 'tomb', to: 'lists#tomb'
  post 'tomb', to: 'lists#tomb_feldolgozo'
  get 'lists_update', to: 'lists#lista_frissites'

post 'login/create'
post 'sessions/create'
get 'login/create', to: 'login#reg'
get "fbn", to: "projects#fajlok_beolvasasa_normal"
get "project_trans_reset", to: "projects#project_trans_reset"
get "ptf", to: "projects#project_tomeges_forditas"
get "ptfo", to: "projects#project_tomeges_forditas_osszes"
post "project_oszlop", to: "projects#project_oszlop"
post "project_szoveg", to: "projects#project_szoveg"
post "project_elvalaszto", to: "projects#project_elvalaszto"
post "project_mentes", to: "projects#project_forditas_mentes"
post "project_nemvalto", to: "projects#project_nemvalto"
post "project_sorvalto", to: "projects#project_sorvalto"
get "project_file_download_kalap", to: "projects#project_file_download_kalap"
get "project_finish", to: "projects#project_finish"
get "project_line", to: "projects#line"
get "project_lines", to: "projects#lines"
get "project_file_zip", to: "projects#project_file_zip"
post "project_line_javitasa", to: "projects#project_line_save"
get "rendezo", to: "projects#rendezo"
post "project_tomeges_csere", to: "projects#tomeges_csere"
post 'project_download', to: "projects#download"
get 'project_download', to: "projects#download"
post 'project_paros', to: "projects#project_paros"
get "project_idezojel", to: "projects#idezojel"
get "project_nyito", to: "projects#nyito"
post "project_idezo_mentes", to: "projects#idezojel_mentes"
post "project_char_on", to: "projects#char_on"
post "project_char_off", to: "projects#char_off"
post "project_regex", to: "projects#regex"
post "translatertouser", to: "user2s#translatertouser"
get "search", to: "search#kereses"
get "searchmagyhu", to: "search#keresesmagyhu"
get "searchtl", to: "search#keresestl"
get "magyhu", to: "magyhu#beolvas"
get "downloadend", to: "games#downloadend"
get "jakab", to: "games#jakab"
get 'download_ticket/:id', to: 'tickets#download_ticket', as: 'download_ticket'
get 'filem', to: "projects#filem"
post 'lobot', to: "games#lobot"
get "hopper", to: "hopps#hopper"
get "regenerated", to: "translaters#regen"

end

app/models/gamereq.rb
class Gamereq < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :game, optional: true
end

app/controllers/gamereqs_controller.rb
class GamereqsController < ApplicationController
  before_action :set_gamereq, only: %i[ show edit update destroy ]

  # GET /gamereqs or /gamereqs.json
  def index
    @gamereqs = Gamereq.where(valasz: nil)
  end

  # GET /gamereqs/1 or /gamereqs/1.json
  def show
    @gamereqs = Gamereq.where(valasz: params[:id])
  end
  def gamereqsnew
    
  end
  def reqsaccept
    if current_user&.admin?

    end
  end
  def reqsdelete
    if current_user&.admin?
    end
  end
  # GET /gamereqs/new
  def new
    @gamereq = Gamereq.new
  end

  # GET /gamereqs/1/edit
  def edit
  end

  # POST /gamereqs or /gamereqs.json
  def create
    @gamereq = Gamereq.new(gamereq_params)

    respond_to do |format|
      if @gamereq.save
        format.html { redirect_to gamereq_url(@gamereq), notice: "Gamereq was successfully created." }
        format.json { render :show, status: :created, location: @gamereq }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @gamereq.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gamereqs/1 or /gamereqs/1.json
  def update
    respond_to do |format|
      if @gamereq.update(gamereq_params)
        format.html { redirect_to gamereq_url(@gamereq), notice: "Gamereq was successfully updated." }
        format.json { render :show, status: :ok, location: @gamereq }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @gamereq.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gamereqs/1 or /gamereqs/1.json
  def destroy
    @gamereq.destroy

    respond_to do |format|
      format.html { redirect_to gamereqs_url, notice: "Gamereq was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gamereq
      @gamereq = Gamereq.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def gamereq_params
      params.require(:gamereq).permit(:gamename, :gamelink, :username)
    end
end

app/helpers/gamereqs_helper.rb
module GamereqsHelper
end

app/views/gamereqs/_form.html.slim
= simple_form_for(@gamereq) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :gamename, label: "Játék neve"
    = f.input :gamelink, label: "Játék link(Steam, Epic...)"
    = f.input :username, label: "Neved", input_html: {disabled:  current_user ? true : false, value: current_user ? current_user.name : '' } 
    = f.input :desc, label: "Kérés:"
   

  .form-actions
    = f.button :submit , "Beküldés", class:"btn btn-success"

app/views/gamereqs/_gamereq.html.slim
div id="#{dom_id gamereq}"
  p
    strong Gamename:
    =< gamereq.gamename
  p
    strong Gamelink:
    =< gamereq.gamelink
  p
    strong User:
    =< gamereq.user_id
  p
    strong Username:
    =< gamereq.username
  p
    strong Game:
    =< gamereq.game_id
  p
    strong Desc:
    =< gamereq.desc
  p
    strong Oke:
    =< gamereq.oke

app/views/gamereqs/edit.html.slim
h1 Editing gamereq

== render "form", gamereq: @gamereq

br

div
  => link_to "Show this gamereq", @gamereq
  '|
  =< link_to "Back to gamereqs", gamereqs_path

app/views/gamereqs/index.html.slim
.container-flex
  .row 
    .col-xs-12.col-md-9.col-lg-10.bg-basic-color
        
        .row
            .col-lg-7.col-xs-12.offset-lg-2
                .bg-dark.rounded.m-2
                    .game-data__download-section.bg-dark.col-lg-8.col-xs-12.offset-lg-2.p-2.rounded-3.text-center
                       

                        - @gamereqs.each do |message|
                            = link_to gamereq_path(id: message), class:"btn btn-primary col-12 col-lg-8 offset-lg-2 text-center mb-4 p-3 rounded" do |link|
                                    h3
                                        | #{message.gamename} »                                                                           
                                    
                                    - if message.user_id.present?
                        
                                        | #{message.user.alias || message.user.name}
                                    -else 
                                        | #{message.username}
                                    br
                                    |  #{message.created_at.strftime("%Y-%m-%d %H:%M")}
                                    br
    .col-xs-12.col-md-3.col-lg-2.bg-grey-color.side-scroll
      = render 'shared/side' 

app/views/gamereqs/new.html.slim
h1 New gamereq

== render "form", gamereq: @gamereq

br

div
  = link_to "Back to gamereqs", gamereqs_path

app/views/gamereqs/show.html.slim
.container-flex
  .row 
    .col-xs-12.col-md-9.col-lg-10.bg-basic-color
      .row
        .col-lg-7.col-xs-12.offset-lg-2
          
            
          .game-data__download-section.col-lg-12.col-xs-12.rounded-3.text-center
            = link_to "« Vissza", gamereqs_path, class:"btn btn-secondary col-4" 
            - if  @gamereq.game_id.present?
              = link_to "A játék oldala »", game_path(@gamereq.game.slug), class:"btn m-2 btn-warning col-4" 
            hr.text-light
            .game-data__download-section.bg-dark.col-8.offset-2.p-2.rounded-3.text-center.text-light
                .row
                  .col.lg-9
                    - if !current_user.present?
                        =label_tag(:username, "Felhasználónév")
                        =text_field_tag(:username, nil, class: "col-12 ")
                        =label_tag(:duma, "Üzenet" ,class:"m-2")
                        textarea id="duma_#{params[:id]}" rows = "5"
                        div class="btn btn-primary btn-block col-5" data-id= "#{params[:id]}" id="forumsubmit2"
                          |Beküldés
                    
                    -if current_user && !current_user.mute?
                      =label_tag(:username, "Felhasználónév")
                      - name = current_user.alias || current_user.name
                      = text_field_tag(:username, name, class: "col-12", readonly: true)
                      =label_tag(:duma, "Üzenet" ,class:"m-2")
                      textarea id="duma_#{params[:id]}" rows = "5"
                      div class="btn btn-primary btn-block col-5" data-id= "#{params[:id]}" id="forumsubmit2"
                        |Beküldés
                    -if current_user && current_user.mute?
                      .col-12.bg-danger
                        |Hozzászólási jogod megvonva, keress meg a discordon(hunatbaf.hu_sediqwe) ha úgy véled, hogy hibáztunk a jog elvételekor.
                  .col-lg-12.bg-info.text-dark.rounded.border-1.m-3.border-light.border
                    |Bejelentkezett tagként automatikusan elfogadásra kerül a hozzászólásod.
                    

            
            - @gamereqs.each do |mes|
              
              .row.bg-dark.mb-4.rounded.text-light
                .col-3.border-right.border-success.p-2 style="text-align: center; border-right: 1px solid #28a745; overflow: hidden;"
                  -if mes.oke || current_user&.admin?

                    - if mes.user_id.present?
                        
                      -if mes.user.photo.present?
                        =image_tag mes.user.photo, size: "100x100"
                        br
                      = mes.user.alias || mes.user.name
                      br
                      -if mes.user.moderator?
                        span class="badge text-bg-info  " Fordító
                        br
                      -if mes.user.admin?
                        span class="badge text-bg-danger " Admin
                        br
                      -if mes.user_id.present? && !mes.user.admin? && !mes.user.moderator?
                        span class="badge text-bg-success" Regisztrált
                        br
                  - if mes.username.present?
                    = mes.username
                    br
                  |#{mes.created_at.strftime("%Y-%m-%d %H:%M")}

                  -if current_user 
                    -if current_user.admin?
                      br
                      = button_to "Destroy this gamereq", @gamereq, method: :delete
                      =link_to "Üzenet törlése", gamereqsdelete_path(id: mes.id), data: {confirm: "Törlöd??"}, class: "btn btn-danger"
                      -if !mes.oke
                        =link_to "OK", gamereqsaccept_path(id: mes.id), data: {confirm: "Elfogadod??"}, class: "btn btn-success"      
                      br
                      
                      -if mes.user.present?
                        -if !User.find(mes.user_id).mute?
                          =link_to "MUTE", gameforumusermute_path(id: mes.user_id), data: {confirm: "Kussoltatod??"}, method: "post", class: "btn btn-success"
                        -if User.find(mes.user_id).mute?                          
                          =link_to "UNMUTE", gameforumuserunmute_path(id: mes.user_id), data: {confirm: "Visszakuss??"}, method: "post", class: "btn btn-success"

                .col-8
                  
                  -if mes.oke || current_user&.admin?
                    = mes.desc
                -if !mes.oke
                  .col-12
                    h3.bg-info 
                      |Ez az üzenet még elfogadás alatt van, beküldő: >
                      -if mes.user_id.present?
                        = mes.user.alias||mes.user.name
                      - if mes.username.present?
                        = mes.username
            = link_to "Vissza", qc_path, class:"btn btn-secondary col-lg-4"
    .col-xs-12.col-md-3.col-lg-2.bg-grey-color.side-scroll
      = render 'shared/side' 



    
    






  